
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Providers from "./Providers";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        style={{margin: 0, padding: 0, boxSizing: 'border-box'}}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
